// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jprdxhtjireowuhchvtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwcmR4aHRqaXJlb3d1aGNodnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NDU5MDIsImV4cCI6MjA1NjQyMTkwMn0.4ZEmtVanDrNDtMWo4eVztReOt2ZwPqGYhESU-Xsu5ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);